<?php
/**
 * Sanitize SVG tags.
 *
 * @return array
 */
function wpcomsp_reactions_kses_svg_allowed_tags(): array {
	return array(
		'svg'            => array(
			'xmlns'        => true,
			'width'        => true,
			'height'       => true,
			'viewbox'      => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
			'aria-hidden'  => true,
			'role'         => true,
			'focusable'    => true,
		),
		'g'              => array(
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'path'           => array(
			'id'           => true,
			'd'            => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'circle'         => array(
			'cx'           => true,
			'cy'           => true,
			'r'            => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'rect'           => array(
			'width'        => true,
			'height'       => true,
			'x'            => true,
			'y'            => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'text'           => array(
			'x'            => true,
			'y'            => true,
			'font-size'    => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'line'           => array(
			'x1'           => true,
			'x2'           => true,
			'y1'           => true,
			'y2'           => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'polygon'        => array(
			'points'       => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'polyline'       => array(
			'points'       => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'ellipse'        => array(
			'cx'           => true,
			'cy'           => true,
			'rx'           => true,
			'ry'           => true,
			'fill'         => true,
			'stroke'       => true,
			'stroke-width' => true,
			'class'        => true,
		),
		'defs'           => array(),
		'lineargradient' => array(
			'id'            => true,
			'x1'            => true,
			'y1'            => true,
			'x2'            => true,
			'y2'            => true,
			'gradientunits' => true,
			'stop-color'    => true,
			'stop-opacity'  => true,
		),
		'radialgradient' => array(
			'id'                => true,
			'cx'                => true,
			'cy'                => true,
			'r'                 => true,
			'fx'                => true,
			'fy'                => true,
			'gradienttransform' => true,
			'gradientunits'     => true,
			'stop-color'        => true,
			'stop-opacity'      => true,
		),
		'stop'           => array(
			'offset'       => true,
			'stop-color'   => true,
			'stop-opacity' => true,
		),
	);
}
